### ISSUE TITLE
Sélection de polygones

### ISSUE THREAD

**Issue by JLHI** [cartoinddigo/iso_ign#4]
Erreur python en cas de sélection de polygone. Ajouter un test de géométrie sur la couche sélectionnée. 

```

_Traceback (most recent call last):
              File "C:\Users/jlhumbert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\iso_ign\iso_ign.py", line 533, in perform_rq_v2
              self.get_iso()
              File "C:\Users/jlhumbert/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\iso_ign\iso_ign.py", line 321, in get_iso
              gx = geom.asPoint().x()
             TypeError: Polygon geometry cannot be converted to a point. Only Point types are permitted._
```

**Comment by cartoinddigo** [comment]
@JLHI :
Fixé avec 
`if ptt.type() == QgsWkbTypes.PointGeometry:`
